#################################################################
## iOS Actionable Notifications
#################################################################

        #################################################################
        ## Washing Machine Switch On
        #################################################################

- alias: iOS Action - Washing Machine Switch On

  trigger:
    - platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: WASHINGMACHINE_TURN_ON_SWITCH

  action:
    - service: switch.turn_on
      entity_id: switch.washing_machine

        #################################################################
        ## Air Cleaner Switch On
        #################################################################

- alias: iOS Action - Air Cleaner Switch On

  trigger:
    - platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: AIRCLEANER_TURN_ON_SWITCH

  action:
    - service: switch.turn_on
      entity_id: switch.air_cleaner

        #################################################################
        ## Hall Closet Light Off
        #################################################################

- alias: iOS Action - Hall Closet Light Off

  trigger:
    - platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: HALLCLOSET_TURN_OFF_LIGHT

  action:
    - service: switch.turn_off
      entity_id: light.hall_closet_lights

        #################################################################
        ## Biocube Pump Switch On
        #################################################################

- alias: iOS Action - Biocube Pump Switch On

  trigger:
    - platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: BIOCUBEPUMP_TURN_ON_SWITCH

  action:
    - service: switch.turn_on
      entity_id: switch.biocube_pump

        #################################################################
        ## Biocube Wavemaker Switch On
        #################################################################

- alias: iOS Action - Biocube Wavemaker Switch On

  trigger:
    - platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: BIOCUBEWAVEMAKER_TURN_ON_SWITCH

  action:
    - service: switch.turn_on
      entity_id: switch.biocube_wavemaker

        #################################################################
        ## Biocube Maintenance Mode Off
        #################################################################

- alias: iOS Action - Biocube Maintenance Mode Off

  trigger:
    - platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: BIOCUBEMAINTENANCE_TURN_OFF_SWITCH

  action:
    - service: switch.turn_off
      entity_id: input_boolean.biocube_maintenance_mode


        #################################################################
        ## Double Garage Close
        #################################################################

- alias: iOS Action - Double Garage Close

  trigger:
    - platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: DOUBLE_GARAGE_CLOSE

  action:
    - service: cover.close_cover
      entity_id: cover.double_garage