#################################################################
## Aquarium - Notifications and Automations
#################################################################

        ##########################################################
        ## Red Sea UV Light - Total Counter
        ##########################################################

- alias: Red Sea UV Light Usage - Total Counter
  trigger:
    - platform: time
      at: '23:59:00'

  action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.redsea_uv_light_usage
        value: "{{ states.sensor.red_sea_aqua_uv_runtime_today.state | float / 24 + states.input_number.redsea_uv_light_usage.state | float }}" 