#################################################################
## Hardware Automation and Notifications
#################################################################

        #################################################################
        ## Home Assistant Startup Success
        #################################################################

- alias: Notification Text - Home Assistant Start

  trigger:
    - platform: homeassistant
      event: start

  action:
    - service: notify.mobile_app_USER1_iphone
      data:
        message: "Home Assistant Started"

        #################################################################
        ## Home Assistant Started Notification
        #################################################################

- alias: Notification Log - Home Assistant Start

  trigger:
    - platform: homeassistant
      event: start
  action:
    service: system_log.write
    data:
      message: "Home Assistant started."

#################################################################
## NAS Warning
#################################################################

- alias: Notification Text - NAS Warning

  trigger:
    - platform: state
      entity_id: sensor.nas_status
      to: 'warning'

  action:
    - service: notify.mobile_app_USER1_iphone
      data:
        message: "NAS RAID Failing"

#################################################################
## UPS Alerts
#################################################################


        ##########################################################
        ## UPS Power Loss Alert
        ##########################################################

- alias: Notification Text - UPS Power Loss Alert

  trigger:
    - platform: state
      entity_id: sensor.ups_status
      from: "Online"
      to: "On Battery Battery Discharging"

  action:
    - service: notify.mobile_app_USER1_iphone
      data:
        message: "Power Outage - UPS Runtime - {{states.sensor.ups_battery_runtime_mins.state}}"

        ##########################################################
        ## UPS Low Runtime Alert
        ##########################################################

- alias: Notification Text - UPS Low Runtime Alert

  trigger:
    - platform: numeric_state
      entity_id: sensor.ups_battery_runtime_mins
      below: 15

  action:
    - service: notify.mobile_app_USER1_iphone
      data:
        message: "15 mins of UPS Battery Remaining!"


        #################################################################
        ## Reload Vera Sensors on Home Assistant Start
        #################################################################

- alias: System - Reload Vera Sensors on Home Assistant Start

  trigger:
    - platform: homeassistant
      event: start

  action:
    - service: homeassistant.update_entity
      data:
        entity_id:
          - sensor.basement_humidity_sensor
          - sensor.basement_light_sensor
          - binary_sensor.basement_motion_sensor
          - binary_sensor.family_room_motion
          - sensor.family_room_humidity_sensor
          - sensor.family_room_light_sensor
          - sensor.basement_temperature_sensor
          - sensor.basement_temperature
          - sensor.family_room_temperature_sensor
