#################################################################
## Magic Mirror Automations
#################################################################

        ##########################################################
        ## Magic Mirror Off when Away
        ##########################################################

- alias: Magic Mirror Off when Away
  id: 'magicmirror_off_away'

  trigger:
    - platform: state
      entity_id: group.family
      from: 'home'
      to: 'not_home'

  condition:
    - condition: state
      entity_id: switch.magicmirror_display
      state: 'on'

  action:
    - service: homeassistant.turn_off
      entity_id: switch.magicmirror_display


        ##########################################################
        ## Magic Mirror On when Home
        ##########################################################

- alias: Magic Mirror On when Home
  id: 'magicmirror_on_away'

  trigger:
    - platform: state
      entity_id: group.family
      from: 'not_home'
      to: 'home'

  condition:
    - condition: state
      entity_id: switch.magicmirror_display
      state: 'off'
    - condition: time
      after: '05:00:00'
      before: '23:00:00'

  action:
    - service: homeassistant.turn_on
      entity_id: switch.magicmirror_display

        ##########################################################
        ## Magic Mirror Hide Weekend Chores
        ##########################################################

- alias: Magic Mirror Hide Weekend Chores
  id: 'magicmirror_hide_weekend_chores'

  trigger:
    - platform: time
      at: '06:00:00'

  condition:
    - condition: time
      weekday:
        - mon

  action:
    - service: homeassistant.turn_off
      entity_id: switch.magicmirror_weekend_chores_display

        ##########################################################
        ## Magic Mirror Show Weekend Chores
        ##########################################################

- alias: Magic Mirror Show Weekend Chores
  id: 'magicmirror_show_weekend_chores'

  trigger:
    - platform: time
      at: '06:00:00'

  condition:
    - condition: time
      weekday:
        - fri

  action:
    - service: homeassistant.turn_on
      entity_id: switch.magicmirror_weekend_chores_display