#################################################################
## Water Treatment System Automations
#################################################################

        ##########################################################
        ## Lift Station Activations Counter and Notification
        ##########################################################

- alias: Lift Station Activations Counter

  trigger:
    - platform: state
      entity_id: sensor.lift_station_status
      to: 'running'
      
  action:  
    - service: counter.increment
      entity_id: counter.lift_station_activations_counter
    - service: counter.increment
      entity_id: counter.lift_station_activations_counter_current_day
    - service: notify.mobile_app_USER1_iphone
      data:
        message: "Lift Station Running - {{states.counter.lift_station_activations_counter_current_day.state}}"
      
        ##########################################################
        ## Lift Station Activations Counter - Daily
        ##########################################################

- alias: Lift Station Activations Counter - Daily
  trigger:
    - platform: time
      at: '23:59:00'

  action:
    - service: counter.configure
      data_template:
        entity_id: counter.lift_station_activations_counter_last_day
        value: "{{ states.counter.lift_station_activations_counter_current_day.state | int }}" 
    - service: counter.reset
      entity_id: counter.lift_station_activations_counter_current_day

        ##########################################################
        ## Lift Station Check System Notification
        ##########################################################

- alias: Lift Station Check System

  trigger:
    - platform: state
      entity_id: sensor.lift_station_status
      to: 'check system'
      for:
        hours: 0
        minutes: 3
        seconds: 0
      
  action:  
    - service: notify.mobile_app_USER1_iphone
      data:
        message: "Lift Station Error - Check Status - {{states.sensor.e6_1_ct1_lift_station_watts.state}}"